import 'package:flutter/material.dart';

class TermsConditionsScreen extends StatelessWidget {
  const TermsConditionsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      appBar: AppBar(
        backgroundColor: Colors.black,
        elevation: 0,
        title: const Text(
          "Terms & Conditions",
          style: TextStyle(color: Colors.white, fontSize: 20, fontWeight: FontWeight.bold),
        ),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios, color: Colors.white, size: 20),
          onPressed: () => Navigator.pop(context),
        ),
        bottom: PreferredSize(
          preferredSize: const Size.fromHeight(1),
          child: Container(color: Colors.white12, height: 1),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Center(
              child: Text(
                "TERMS OF USE",
                style: TextStyle(fontWeight: FontWeight.bold, fontSize: 22, color: Colors.white),
              ),
            ),
            const SizedBox(height: 24),
            _sectionTitle("A) INTRODUCTION"),
            _bodyText("Welcome to the mobile application ‘Chai Shots’, an on-demand digital audio-video streaming service/platform (the “App”) owned, operated, managed, and distributed by Chai Shots Private Limited, a company incorporated under the laws of India, having its registered office at Plot no. 206, House No.3, Kavuri Hills, Hyderabad, Telangana, India - 500033 IN (hereinafter referred to as “Company”, “we”, “us”, or “our”, which shall include its successors and permitted assigns), in accordance with and subject to these terms of usage (“Terms”, “Terms of Use”). We offer this App including all information, tools and services available from this mobile application to You, the user (“User” or “You” “Your”) conditioned upon Your acceptance of all terms, conditions, policies and notices stated here (which shall be amended from time to time) within the Territory. For the purposes of the Terms, “Territory” shall mean worldwide including India."),
            _bodyText("This document is a legally binding document entered into between the Company and the User and You agree to access the Content (defined below) as per these Terms. These Terms are an electronic record and governed by and in accordance with the provisions of the Information Technology Act, 2000, the Information Technology (Amendment) Act, 2008, and the rules framed thereunder as applicable including the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 (“IT Act”), and amended from time to time. This electronic record is generated by a computer system and does not require any physical or digital signatures."),
            _bodyText("For the purpose of these Terms, “Content” refers to any and all audio-visual content including videos, sound recordings, musical compositions, graphics, photographs, texts (including comments and scripts), branding (including trade names, trademarks, service marks or logos), software, metrics and other materials made available through the App, whether owned by the Company or licensed from third parties, including without limitation, short series, clips, trailers, promotional videos, or similar content."),
            _bodyText("By downloading, installing, registering on, accessing, or using the App in any manner, You expressly acknowledge that You have read, understood, and agreed to be bound by these Terms of Use, our Privacy Policy, and any additional guidelines, rules, terms, or disclaimers posted on the App or otherwise notified to You from time to time, all of which are incorporated herein by reference (collectively, the “Agreement”)."),
            _bodyText("If you do not agree with these Terms or our privacy policy, You must stop using the App. Continued use means You accept the Terms, including any changes we may make. Unauthorized use may lead to suspension, termination, or legal action."),
            
            _sectionTitle("B) ELIGIBILITY, FREE CONTENT & REGISTRATION"),
            _subTitle("Eligibility to Use the App"),
            _bodyText("The services offered by the App are intended for individuals who have reached the age of majority in the Territory (“Age of Majority”). In all circumstances, only individuals who are of the Age of Majority may create an Account on the App, and such individuals will remain fully responsible for the use and management of that Account. By accessing the App, you represent and warrant that You have reached the legal Age of Majority as per Applicable Laws."),
            _bodyText("For the purpose of the Terms Of Use, “Applicable Laws” means all laws, rules, regulations, and guidelines applicable within the Territory."),
            _subTitle("Registration and Account creation"),
            _bodyText("Creation of account: In order to access or view, any Content that is not classified as Free Content, You are required to mandatorily create an Account on the App. You understand and agree to provide accurate and verifiable details, specifically Your mobile number, for the purpose of creating and maintaining Your account on the App and for conducting any Know-Your-Customer (KYC) process, as applicable. You confirm that the information provided is true and accurate in all respects. Your registration shall be verified via a one-time password (OTP) sent to Your mobile number, upon which a valid “Account” shall be created and a unique user profile shall be tied to Your registered mobile number and login credentials."),
            
            _sectionTitle("C) ACCESS OF CONTENT AND USER’S DISCRETION"),
            _bodyText("Users may stream content on up to two (2) devices simultaneously per Account. Any attempt to exceed this limit through credential sharing, unauthorized access, or use of automated tools may result in suspension or termination of the Account."),
            _bodyText("You understand that the App may include Content with explicit language, sexual material, violence, or mature themes, some of which may not be labelled or may appear in search results unintentionally. Such Content may not be suitable for all Users, and You agree to use the App at Your own risk. The App and its affiliates are not liable for any Content You may find offensive. User discretion is advised."),
            _bodyText("Access to the App will be available to You in accordance with the Applicable Laws of the Territory."),
            
            _sectionTitle("D) FEATURES"),
            _bodyText("The App may offer various and/ or amend integrative services within the App at its sole and exclusive discretion."),
            _subTitle("Clap feature"),
            _bodyText("The Clap feature allows Users to show appreciation to the cast and crew of Content, as identified and made available by the Content producer to the Company, through the App. Each Clap shall consist of both (i) a short note of appreciation (up to 300 characters); and (ii) a monetary appreciation payable only in denominations specified on the App (currently ranging from INR 20 to INR 10,000) sent via the Company through the App using the available Payment Methods. Notes are designed to be shared together with a monetary appreciation, and cannot be sent on a standalone basis. All monetary rewards contributed through the Clap feature shall be directed to the intended cast or crew member(s), subject to deduction of applicable taxes and third-party charges (including payment processing fees and platform commissions). Claps, once made, are final and non-refundable under any circumstances."),
            _subTitle("Promotions"),
            _bodyText("From time to time, the Company may, at its sole discretion, introduce and administer promotional offers, campaigns, reward systems, gamification models, or incentive programs (“Promotions”), which may include but are not limited to the use of digital rewards such as bonus credits, or other forms of benefits. Such Promotions are designed solely for user engagement and entertainment and shall not be construed as creating any monetary or property interest in favor of the User. The availability, eligibility, duration, redemption mechanism, and value of such Promotions shall be determined exclusively by the Company and may be modified, suspended, or withdrawn at any time without prior notice. The Company’s decisions in respect of Promotions shall be final and binding. The User shall have no right to dispute, claim, or demand continuity, cash equivalence, transferability, or redemption beyond what is expressly permitted by the Company."),
            _subTitle("Compatibility Systems/ Accessibility"),
            _bodyText("The App is officially available for download only through the Apple App Store and Google Play Store. The App works on devices that meet system and compatibility requirements, which may change over time. A device that is compatible now may later become incompatible due to updates by us or applicable third parties, from time to time. Updates to the App (automatic or manual) and, in some cases, to Your device may be required for continued access. Playback and streaming quality depend on factors such as Your device, internet connection, and chosen settings. The App may adjust resolution automatically to prevent interruptions to Your viewing experience. While we aim to provide a high-quality experience, we cannot guarantee and be liable for specific quality or resolution, even for paid premium Content."),
            
            _sectionTitle("E) ACCESS PLANS AND PAYMENTS"),
            _bodyText("Content (excluding Free Content) shall be made available/ accessible to You via the following methods, either simultaneously, or exclusively:"),
            _subTitle("Streaming Plan"),
            _bodyText("Users may access Content on the App by subscribing to a plan made available by the Company (each, a “Streaming Plan”) and paying the applicable fee as displayed at the time of purchase (the “Streaming Fee”)."),
            _bodyText("Each Streaming Plan shall provide access to all Content for a defined duration (the “Viewing Period”), which may be monthly, yearly, or as otherwise specified on the App for the respective Streaming Plan. The Streaming Fee for a Streaming Plan, once paid, shall remain fixed for the applicable Viewing Period."),
            _bodyText("The Company reserves the right to revise Streaming Fees at its sole discretion. Any such revision shall only apply prospectively to future purchases or renewals and shall not affect the Streaming Fee already paid for an ongoing Viewing Period."),
            _bodyText("Streaming Plans may automatically renew at the end of the applicable Viewing Period with prior notice unless cancelled by the User prior to the renewal date, in which case the User’s Payment Method shall be charged the applicable Streaming Fee."),
            _subTitle("Other access models"),
            _bodyText("App may, from time to time, introduce alternative Content access models, in addition to or in substitution of the existing options. Unless specifically governed by separate terms, such models shall be interpreted in accordance with the general principles laid out in the Terms of Use. Users are expected to refer to promotional pages, in-App instructions, and App notifications for specific access rules. Continued use of such access constitutes deemed acceptance of applicable conditions, even if not explicitly listed herein."),
            _bodyText("The names and descriptions of such access models may change from time to time; however, the nature and terms applicable shall be interpreted consistently with the prevailing models outlined herein. In cases where specific terms are not expressly defined for a newly introduced model, Users are expected to exercise discretion and follow the general principles of Content access, payment usage, and conduct defined in these Terms. Access to Content ceases immediately upon cancellation or failure to renew."),
            
            _sectionTitle("F) PAYMENT"),
            _bodyText("Content on the App shall become available to You once the applicable Fee has been successfully received. Please note that payment processing may take additional time depending on the Payment Method, and certain providers of Payment Methods may also levy transaction charges."),
            _bodyText("All Fees are inclusive of applicable taxes. Upon confirmation of payment of Fee, an electronic invoice shall be issued to You."),
            _bodyText("In the event that Your primary Payment Method fails, the App may, where available, attempt to process the Fee through an alternate Payment Method. If no such Payment Method is available or the attempt fails, access to the Content may be denied."),
            _bodyText("Other than confirming whether a payment has been received, the App shall not be responsible and /or liable for any delays, misuse of information, or losses by third-party processors. In case of any issues with payments, You may reach out to us via the ‘help’ section in the App or @support@chaishots.in."),
            _bodyText("The App reserves the right to modify, discontinue or update Streaming Plan, Viewing Periods, Fees or payment cycles at its sole discretion with notice as per this Terms of Use. Any such changes shall take effect once You next use the App. If You do not agree with the updated terms, it shall be Your responsibility to cancel Your access plan prior to continued use."),
            _bodyText("All Fees are strictly non-refundable, including in cases of partial usage or cancellation of a plan. Once activated, plans shall remain in effect for their full term and cannot be altered during such period."),
            
            _sectionTitle("G) REFUNDS & CANCELLATION"),
            _bodyText("Refunds of Fee, as applicable, are processed only and specifically in the event of failure to access Content despite successful payment due to a direct issue with the App. Refund requests must be sent to support@chaishots.in or via the ‘help’ section in the App within seventy-two (72) hours of the issue. Other reasons save and except as stated above, including without limitation dissatisfaction with Content, early exit from a show, or unused balance shall not be considered grounds for refund."),
            _bodyText("Once refund is approved post inspection by our team, the refund will be credited to the original model of payment within 7-10 working days."),
            
            _sectionTitle("H) HOLDBACK / RESTRICTIONS ON USE OF CONTENT"),
            _bodyText("By using the App, You agree to not, directly or indirectly: Exploit Content, Bypass Protections, Unauthorized Access & Use, Unlawful or Offensive Conduct, Intellectual Property Violations, Account Misuse, Encumbrances, Public Use."),
            _bodyText("If You violate any part of this clause, App reserves the right to restrict, suspend, or permanently terminate Your access to the app and services without notice."),
            
            _sectionTitle("I) CONTENT & OWNERSHIP"),
            _bodyText("All rights, title, interest in the App and the Content available on the App, including but not limited to all its constituents, short series, video clips, layout, images App is owned by or licensed to the App and/ or Company and is protected by Applicable Laws Indian and international intellectual property laws. The App retains and reserves all titles in and to the Intellectual Property Rights in perpetuity around the world and for all languages."),
            
            _sectionTitle("J) GRIEVANCE REDRESSAL"),
            _bodyText("If You have any complaints regarding the App, Your access to the App, please contact the App at support@chaishots.in. Grievance Officer: Ms. Nairmalya Suryadevara. Address: Plot no. 206, House No.3, Kavuri Hills, Hyderabad, Telangana, India - 500033 IN."),
            
            const SizedBox(height: 48),
            const Center(
              child: Text(
                "© 2026 Chai Shots Private Limited",
                style: TextStyle(color: Colors.white38, fontSize: 12),
              ),
            ),
            const SizedBox(height: 40),
          ],
        ),
      ),
    );
  }

  Widget _sectionTitle(String title) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 16.0),
      child: Text(
        title,
        style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 18, color: Colors.white),
      ),
    );
  }

  Widget _subTitle(String title) {
    return Padding(
      padding: const EdgeInsets.only(top: 12.0, bottom: 8.0),
      child: Text(
        title,
        style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 15, color: Colors.white70),
      ),
    );
  }

  Widget _bodyText(String text) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 12.0),
      child: Text(
        text,
        style: const TextStyle(color: Colors.white60, fontSize: 14, height: 1.6),
      ),
    );
  }
}
